#!/bin/sh
set -e
repo="$(pwd)"
zipper="${repo}/external/bazel_tools/tools/zip/zipper/zipper"
archive="${repo}/bazel-out/k8-fastbuild/bin/release/v2ray-windows-32.zip"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/zip_file.XXXXXXXXXX")"
cd "${tmp}"
ln -sf "${repo}/release/config/config.json" "${tmp}/config.json"
ln -sf "${repo}/release/config/vpoint_socks_vmess.json" "${tmp}/vpoint_socks_vmess.json"
ln -sf "${repo}/release/config/vpoint_vmess_freedom.json" "${tmp}/vpoint_vmess_freedom.json"
ln -sf "${repo}/release/config/geoip.dat" "${tmp}/geoip.dat"
ln -sf "${repo}/release/config/geosite.dat" "${tmp}/geosite.dat"
ln -sf "${repo}/bazel-out/k8-fastbuild/bin/infra/control/main/windows/386/0/v2ctl.exe" "${tmp}/v2ctl.exe"
ln -sf "${repo}/bazel-out/k8-fastbuild/bin/infra/control/main/windows/386/0/v2ctl.exe.sig" "${tmp}/v2ctl.exe.sig"
ln -sf "${repo}/bazel-out/k8-fastbuild/bin/main/windows/386/0/v2ray.exe" "${tmp}/v2ray.exe"
ln -sf "${repo}/bazel-out/k8-fastbuild/bin/main/windows/386/0/v2ray.exe.sig" "${tmp}/v2ray.exe.sig"
ln -sf "${repo}/bazel-out/k8-fastbuild/bin/main/windows/386/0/wv2ray.exe" "${tmp}/wv2ray.exe"
ln -sf "${repo}/bazel-out/k8-fastbuild/bin/main/windows/386/0/wv2ray.exe.sig" "${tmp}/wv2ray.exe.sig"
find . | sed 1d | cut -c 3- | LC_ALL=C sort | xargs "${zipper}" cC "${archive}"
cd "${repo}"
rm -rf "${tmp}"